language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test:coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - npm run build
deploy:
      provider: pages
      skip_cleanup: true
      github_token: $github_token
      local_dir: dist
      on:
        branch: master
on:
  branch: master
